### ISSUE TITLE
Error - "host not found in upstream 'app' in /etc/nginx/conf.d/default.conf:14"

### ISSUE THREAD

**Issue by atthijs98** [smithmicro/n7m#11]
I am trying to set up the n7m project following the provided installation guide. However, I encountered an error when attempting to run the docker-compose run command. The error message is as follows:

`n7m-web-1 | 2023/08/02 07:24:40 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/conf.d/default.conf:14
n7m-web-1 | nginx: [emerg] host not found in upstream "app" in /etc/nginx/conf.d/default.conf:14`

**Steps to Reproduce:**

1. Clone the n7m project from the GitHub repository.
2. Run docker-compose build to build all the required images.
3. Download Wikimedia data and country grids by running docker-compose run feed download --wiki --grid.
4. Download this .obf file from geofabrik: https://download.geofabrik.de/europe/netherlands/drenthe-latest.osm.pbf and place it into /data/tileset
5. Edit the OSM_FILENAME environment variable in the docker-compose.yml file to select the downloaded OSM file.
6. Run docker-compose up to start the containers.

**Actual Result:**
Encountered the error mentioned above during the execution of docker-compose run.

**Expected Result:**
The containers should start successfully, and the application should be accessible at http://localhost:8080.

**Additional Information:**

Docker version: 23.0.5
Docker Compose version: 2.17.3
OS: windows 11

Please let me know if any further information is required to troubleshoot this issue. Thank you for your assistance.

**Comment by dsperling** [comment]
The repo lacked a few things that made it work from Windows Docker.  Fix committed to the `feature/nginx1.24` branch. Give this a try:
```
git clone --branch feature/nginx1.24 https://github.com/smithmicro/n7m
```

**Comment by dsperling** [comment]
PR #13 merged
